### ISSUE TITLE
AG based AP missing in 9.6

### ISSUE THREAD

**Issue by 4ljndr0** [phobos2077/fo2_ecco#10]
I've loaded EcCo twice and the AG based AP is missing in 9.6. I haven't had in issues in the previous versions. Thanks!

**Comment by phobos2077** [comment]
I removed it. Instead I buffed Bonus Move perks and decreased minimum level.

**Comment by 4ljndr0** [comment]
> I removed it. Instead I buffed Bonus Move perks and decreased minimum level.

Great. Thank you!

**Comment by phobos2077** [comment]
The old mechanic is still there, you can configure this in BONUS_MOVE section of combat.ini.
