### ISSUE TITLE
"gl_melee_gore_unlock.int" under certain conditions causes the attack animation to fail

### ISSUE THREAD

**Issue by dekrus** [phobos2077/fo2_ecco#11]
After killing a creature, the next attack that should lead to the death of another creature, for which the “script” returns a not entirely correct death animation, leads to the attack being "fizzled", while the "AFTERHITROLL" and "COMBATDAMAGE" hooks are called as in a real attack.

[Savegame before bug](https://github.com/user-attachments/files/15552041/SLOT07.zip) In this save, the bug occurs 10 out of 10 times if after an attack the Vic should die.
[Video of the bug](https://disk.yandex.ru/i/85H512xW9qNq-A)

After deleting the script itself or removing "set_sfall_return" in "HOOK_DEATHANIM2" in "gl_melee_gore_unlock.int", the bug does not occur.

RPU v29 +Sfall v4.4.3.1 + EcCo V0.9.6

Used mods:   
InventoryFilter.dat
cassidy_head.dat
cassidy_voice_joey_bracken_hq.dat
f2_res.dat
fo2tweaks.dat
npc_armor.dat
party_orders.dat
rpu.dat
rpu_enhanced_worldmap.dat
rpu_extended_flamer.dat
rpu_improved_mysterious_stranger.dat
rpu_map_update.dat
rpu_rifle_animations.dat
rpu_wakizashi_animations.dat
rpu_y_ecco.dat
talking_heads.dat
talking_heads_audio.dat
talking_heads_map_update_patch.dat

**Comment by phobos2077** [comment]
А можно по русски, проблема в том что у Вика внезапно броня исчезает?

**Comment by phobos2077** [comment]
Похоже есть какой-то конфликт с опцией no_drop_items_on_death в fo2tweaks. Если отключить её то вроде не ломается.

**Comment by dekrus** [comment]
Проблема в том что после убийства в свой ход, при попытке атаковать Вика (нажать на него мышью в режиме прицела) , если движок урон будет смертельным, то первый раз происходит срабатывание крючков "AFTERHITROLL" and "COMBATDAMAGE" и снятие брони с Вика, без анимации атаки и без нанесения урона, а потом всё срабатывает как надо. 

Да, ещё и конфликт с NPC Armor Appearance в "HOOK_INVENWIELD". Если убрать проверку на смену брони, то тоже не ломается.

**Comment by dekrus** [comment]
Вообще странно, в fo2tweaks только  ANIM_electrified_to_nothing и ANIM_exploded_to_nothing в deathanim2 проверяются, от плазмы не должно такое случаться.

А баг с отсутсвием анимации атаки, только если атака по площади (гранаты). Точечная атака также вызывает смену брони у напарников, но не прерывает анимацию

**Comment by phobos2077** [comment]
Но есть вероятность что с проблема останется. Надо проверить тоже самое только с электро или взрывной атакой. Вот что в логе:

```
sequencing attack...

gl_g_no_drop_items_on_death: moved inventory from Vic to temp box
Something went wrong with a ranged attack sequence!
```
Последняя строка это движок. Ломается скорее всего из-за попытки поменять FID персонажа при снятии с него брони. Решение: не удалять броню в его скрипте.

**Comment by dekrus** [comment]
> Но есть вероятность что с проблема останется. Надо проверить тоже самое только с электро или взрывной атакой. Вот что в логе:
Проверил. Может я чтото не так делал, но всё очень странно, у меня баг именно с невозможностью атаки происходит только с Виком одетым в силовую броню и с плазменным уроном, другие типы урона и напарники хоть и снимают броню перед смертью, но не предотвращают саму атаку.

**Comment by phobos2077** [comment]
Ну они всё равно не должны "снимать" броню перед смертью. Тут явно нужно доработать оригинальный мод. Как я написал выше.

**Comment by WNC12k** [comment]
У меня было что то подобное, только на моем персонаже. Когда я кинул простую гранту и подорвал себя - у чузена пропала кожанка, и уже в комбинезоне произошла анимация смерти

**Comment by phobos2077** [comment]
> У меня было что то подобное, только на моем персонаже. Когда я кинул простую гранту и подорвал себя - у чузена пропала кожанка, и уже в комбинезоне произошла анимация смерти

В теории может быть та же проблема с fo2tweaks, если граната нанесла такой урон что чузена разнесло на части.

**Comment by burner1024** [comment]
NPC Armor тоже надо править или там все ок?

**Comment by phobos2077** [comment]
Думаю что проблема именно в том что смена брони меняет FID. А без NPC Armor в ваниле такое происходит только с ГГ.
