### ISSUE TITLE
radiated effects with geiger counter 0?

### ISSUE THREAD

**Issue by asin1987** [phobos2077/fo2_ecco#13]
I got the expert excrement expeditor perk from Broken Hills, which irradiated me (not sure if that's RP or EcCo modification, but the +5% speech isn't 'free' anymore). Used radaway and fish soup. Geiger counter reads 0, but my strenght dropped by 1 and I'm still irradiated in the character screen ('radiated' was light blue for a day, then turned red and I lost some strength). Impossible to get rid of, no amount of waiting/radaway/visitng the doc in Vault City fixes the radiated status. Is this supposed to happen?

I have RPU 2.3.3u29 Sfall 4.4.3.1, latest EcCo

[
![radiated](https://github.com/phobos2077/fo2_ecco/assets/98592758/12761f29-c79b-49cd-b08e-ce649a947f8f)
](url)

**Comment by phobos2077** [comment]
I don't know about this perk, haven't touched it. Upload your save, so I can take a look at it. In the meantime you can try fixing it with a save editor.
