### ISSUE TITLE
I have Ecco combat set to drop weapons at 0 but guys are still dropping their weapons.

### ISSUE THREAD

**Issue by apollodeathstar** [phobos2077/fo2_ecco#15]
I have these settings but enemies are still dropping weapons in combat. It must be because of critical hit to arms. how do I disable this? I can't get the guns sometimes because I can't see them among the bodies.
```
[CRITTER_LOOT]
;set >0 to enable weapons dropping to the ground on death with a given percentage chance
weapon_drop_chance=0

; max distance the weapon drops in tiles
weapon_drop_dist=0

; direction to where weapon drops: -1 - random, 0..5 - specified direction relative to critter facing (0 means forward, 3 backward)
weapon_drop_dir=0
```

**Comment by phobos2077** [comment]
Try `drop_flag_fix`

**Comment by apollodeathstar** [comment]
> Try `drop_flag_fix`.
> 
> I recommend to use item highlight mod from sfall, I don't have any issue picking up items. Even if they are obscured by bodies sometimes, they are still clickable.

Thanks I will give it a shot.

**Comment by phobos2077** [comment]
The benefit of having more weapons lying around is that AI will seek out and pick up those guns, which makes for a more dynamic combat.

**Comment by apollodeathstar** [comment]
And I love that. Problem is that they pick up unbroken guns and then die and destroy them. Which would be fine if I was also not having a very hard time picking up the guns that are dropped. I have item highlights on but also body highlights so it's very hard to see them and there is no why I know how to cycle the highlights in game. That would be a nice feature. Also with the destruction at 50% I feel very forced to knock these guys out and look them before they can destroy their weapon. It's like I'm playing xcom or something. I feel different attacks should effect the destroyed equipment/weapons differently depending on weapon used and if it was a targeted attack or not. Bursts should have a high chance along with very high destruction weapons like miniguns or GL. A bare fist should be very low and it should also be low if they are knocked down or unconscious.

**Comment by apollodeathstar** [comment]
Also were body hit tables reworked for knockouts etc? If so is there a new table somewhere? As normally groin hit cause more knockouts than head hits but feels different in ecco

**Comment by phobos2077** [comment]
> That would be a nice feature. Also with the destruction at 50% I feel very forced to knock these guys out and look them before they can destroy their weapon.

First of all, in the next version it will be 35%. And also the algorithm ensures the very first time enemy with a given weapon type dies, it is never destroyed. So your chance to get a hold on a new weapon for the first time remains as long as you can find it on the ground :D

**Comment by phobos2077** [comment]
> Also were body hit tables reworked for knockouts etc? If so is there a new table somewhere? As normally groin hit cause more knockouts than head hits but feels different in ecco

Yes, I changed critical tables in 0.9.6, but not by a lot. As you can see here, I only changed effects for arms and legs: https://github.com/phobos2077/fo2_ecco/blob/master/scripts_src/_pbs_main/gl_pbs_critical_table.ssl

**Comment by phobos2077** [comment]
I've adjusted sfall highlighting script, you can now set separate color for corpses: https://drive.google.com/file/d/1HlaI-scdGtthmHfm6aZmF0etWAFclByj/view?usp=sharing

In mods\sfall-mods.ini
```
OutlineColor=16

OutlineColorCorpses=4

OutlineColorContainers=4
```

**Comment by apollodeathstar** [comment]
thanks this helped allot!!

**Comment by phobos2077** [comment]
Btw, I liked these color better:

```
OutlineColor=14592
OutlineColorCorpses=1280
OutlineColorContainers=1280
```
