### ISSUE TITLE
Enemies don't give XP when you kill them

### ISSUE THREAD

**Issue by KabbaCallisto** [phobos2077/fo2_ecco#17]
Something I noticed immediately after installing 0.9.7. I started a new game, noticed no enemy dropped XP when I killed it, so i tried with another save made after and it still didn't work. I tried to fix the issue because someone had the same one in Fallout 1, wihtout this mod, but it doesn't seem to have gone anywhere.

**Comment by KabbaCallisto** [comment]
just sorta using the save editor to add XP in to fill in the blanks, so all isn't lost (also i know this isn't on topic but i'm really lost on what items you need to craft stuff and what other stuff you need, sorry if this is annoying but if you can help that would be nice)

**Comment by phobos2077** [comment]
Hm, that's weird. Someone else reported the same issue before but I could never reproduce it. Can you verify that you don't get actual XP or just the message about getting it? 

How did you install the mod and what other mods do you use?

**Comment by KabbaCallisto** [comment]
ah, it doesn't actually give me XP at all, as for installing it since i had 0.9.6, i just installed it the same way, with the exe. i did also move the inis out of the ecco folder in the mods folder after it was installed, due to some suspicion. Attached are my mods and my modlist.txt 
![2](https://github.com/phobos2077/fo2_ecco/assets/174278278/a3a44ee2-7eeb-41d5-affa-b6aa56eacf1d)
![1](https://github.com/phobos2077/fo2_ecco/assets/174278278/47b5aa53-0926-4f53-9972-af56cc1ca47b)

**Comment by phobos2077** [comment]
> i did also move the inis out of the ecco folder in the mods folder after it was installed, due to some suspicion

Why did you do that? That's most likely is the reason.

**Comment by KabbaCallisto** [comment]
> > i did also move the inis out of the ecco folder in the mods folder after it was installed, due to some suspicion
> 
> Why did you do that? That's most likely is the reason.

yup, undoing that fixed it- sorry to waste your time, but thanks a lot for helping :D

**Comment by Lichtenshtein** [comment]
This could happen because of this line here in ddraw.ini:

> ;Uncomment the option to specify an additional folder path for scripted ini configuration files
> ;the game will search the ini files relative this directory, if the file is not found, the search will proceed relative the root directory of the game
> ;The maximum length of the specified path is 61 characters
> IniConfigFolder=mods\
> ;IniConfigFolder=mods\iniConfigs\

If this line has been modified (in my case to "IniConfigFolder=mods\iniConfigs\"), then this causes a conflict with ecco. No XP for killings, maybe more. I was in Klamath killing geckos when i noticed i'm not leveling at all.

**Comment by phobos2077** [comment]
> Will the game read the scripts ini files from the scripts.dat\ folder, or should they be in the mods\ folder?

The ini files don't care where the scripts are located, these are 2 separate things. 

I didn't think about this setting. It appears it can completed break not only Ecco but all your mods. Thanks for the observation, I would probably add this to installer/readme.
