### ISSUE TITLE
Advanced Power Armor in inventory uses "2MMEC.FRM".

### ISSUE THREAD

**Issue by Dumbisted** [phobos2077/fo2_ecco#18]
![스크린샷 2024-07-01 144136](https://github.com/phobos2077/fo2_ecco/assets/52318642/06789435-16d8-4d7c-9ce1-cbc1149b1fec)
![Converted_scr00042](https://github.com/phobos2077/fo2_ecco/assets/52318642/cffeff01-3e7b-48d3-b204-9c1c7559f4b7)

- Version: 0.9.7v

Just found this today, because I've not visited Navaro until now. Advanced Power Armor MK II uses correct FRM.

Checked pre-0.9.5v does not have this issue; don't know if it has been swapped since 0.9.6v.

**Comment by phobos2077** [comment]
I will fix it, thanks for the report.
