### ISSUE TITLE
Weapon Suggestion) Browning M2?

### ISSUE THREAD

**Issue by Dumbisted** [phobos2077/fo2_ecco#19]
Becasue there is .50 Cal rounds in the mod and Tactics already has resources for it; Totally good condition to do it, right?

---------------

Actually I'm _half-joking_ as even if you really add it, the gun won't be easily usable until a player has bought tons of .50 Cal rounds enough for assault the Oil Rig- Also notice .50 Cal ammos are really hard to be found and stored much,(Just like 2MM EC rounds) unlike most of any other ammos.

Or I can do add it then test it myself, if you could speak me how to add new weapons(I've tried to make new weapons in ProtoManager, but failed to add it in the game's "weapon list" since I have no knowledge for how to do it). I'll be deeply appreciated if you do so.

**Comment by phobos2077** [comment]
Yes, it had a thought about M2 a long time ago and it just doesn't work for the game. With semi-realistic stats, it will be way overpowered. Horrigan will just die from one or two bursts like a baby.

But if you want to add it the easiest way is to just spawn it with a save editor after you added it with Proto Manager. To add new sprite you also need to unpack and edit art/inven/inven.lst

**Comment by Dumbisted** [comment]
Much appreciated for the answer. I can't wait to do it myself!

**Comment by Dumbisted** [comment]
[![My first attempt](https://img.youtube.com/vi/2NYFKV6jmxY/0.jpg)](https://www.youtube.com/watch?v=2NYFKV6jmxY)

All right, I did it. If there is M2 in the mod, it will probably be like in the video.

An overall concept for the M2 I think is "Post-ending bonus weapon"(As the weapon requires a mountain of .50 Cal rounds), but fires only 4 rounds per burst as the weapon has slow RPM.

Since it's just a showcase of "How it would be", I don't think I'll release it...

----------------------------------------------------------------------

Anyway, Once again, Huge appreciate for your instruction and the mod which made me able to do it <3

**Comment by Dumbisted** [comment]
Glad you say so!
