### ISSUE TITLE
Marcus cannot use Bozar AMR (and Cassidy can)

### ISSUE THREAD

**Issue by olivercarlson** [phobos2077/fo2_ecco#2]
The Bozar AMR has Animate Code "P" (custom) instead of "K" (BIg Gun) which means Marcus can no longer use it and Cassidy can. 

Anyways, I fixed it for myself and uploaded a zip with the change if you are interested in adding this change to Ecco.
[00000350.zip](https://github.com/phobos2077/fo2_ecco/files/12242818/00000350.zip)

**Comment by phobos2077** [comment]
This was intended because Bozar is a AMR now, not a machine gun. If you want to give MG to Marcus, just give him LSW or M60.

**Comment by olivercarlson** [comment]
Ok, thanks for the fast reply, closing.
