### ISSUE TITLE
Attempt to make Party Member to equip best weapon available crashes game.

### ISSUE THREAD

**Issue by Dumbisted** [phobos2077/fo2_ecco#22]
[debug.log](https://github.com/user-attachments/files/16554690/debug.log)
[SLOT01.zip](https://github.com/user-attachments/files/16554724/SLOT01.zip)
[mods_order.txt](https://github.com/user-attachments/files/16554727/mods_order.txt)

---------------

kcsulik: USED PARTY MEMBER OPTIONS

Loading current save-file version (2)Starting lipsynch speechLoading sound file ib2p1xx1.ACM...succeeded.
Loading sound file ib2lu1x1.ACM...succeeded.
Ending lipsynch systemChoosing fidget 3 out of 3
Loading sound file ib2p1xx1.ACM...succeeded.
Loading sound file ib2lu1x1.ACM...succeeded.

Error during execution: Bad opcode 0 
Current script: scripts\gl_pbs_ai.int, procedure calc_effective_dtdr

---------------

Just tried to let Sulik equip **_P90 loaded with 10mm JHP_** then the game crashed. P90 with 10mm AP does not have the issue, tho.

I don't know which thing is causing the bug, but the debug.log mentions "gl_pbs_ai.int" in the log so I'm posting it here.

Mod version: 0.9.7
Sfall version: 4.4.4

**Comment by phobos2077** [comment]
Although the game doesn't crash for me, the AI function is definitely broken.
