### ISSUE TITLE
идея: Cheezy Poofs - опыт и\или деньги за кормление Мозга.

### ISSUE THREAD

**Issue by QweSteR2221** [phobos2077/fo2_ecco#26]
В Геско обитает умный кротокрыс Мозг. Его можно покормить Cheezy Poofs (в русской версии Сырные орешки). Но за кормление игрок ничего не получает. И сам же игрок есть Cheezy Poofs не может (но если не реализовано в моде). В итоге они годятся только на продажу. Предложение:

Стоимость Cheezy Poofs - 5 монет (с ВИКИ). Предлагаю начислять игроку по 10 ОО и 10 монет за каждую скормленную упаковку. Если будет скормлено 10 упаковок, то игрок дополнительно получит 100 опыта. 
Один из гулей (у него над головой появится сообщение) скажет (предположим реплика). Мозг был бы очень счастлив получить больше. А при наборе 10 скажет "похоже Мозг обожрался Cheezy Poofs и сейчас не хочет ещё".

Т.е. такая неотмеченная фича\квест. 
Почти аналог сбора журналов и алкоголя.
Всегда приятно когда есть такие мелочи. В Фолле таких много, я и не сам их помню.

**Comment by phobos2077** [comment]
Экко про бой и экономику. Это предложение уместнее в RPU.

**Comment by QweSteR2221** [comment]
раз про мясо шла речь.., то почему бы вот это не сделать. я так подумал. было бы куда девать...
