### ISSUE TITLE
Cannot return stolen items in Den

### ISSUE THREAD

**Issue by kkolyan** [phobos2077/fo2_ecco#4]
My spear vanished in Den. I've found it within Tubby, but cannot get it back.
1. it was in weapon slot. is it ok for kids to steal from weapon slot? seems too unrealistic and limiting for player (character knows they steal, because Flick told, so he keeps valuable items in hands). Though, I'm not sure if it's not a vanilla thing.
2. even before my spear vanished, I checked with "steal" skill each kid after each "steal" animation they performed on me after I went by. there wasn't any item in their inventory. I remember that in vanilla you could immediately steal back from these kids the item they just stole.
3. After discovering miss I visited Flick and Tubby and my spear was among Tubby barter items. So I tried to return my spear with a force. But there is a very limited number of items on his corpse... I understand that Ecco intentionally keep barter things in separate inventory to prevent easy dressing at the early game stage, but that's a pity that one cannot recover stolen item that way. Seems like pretty role-playing case.

**Comment by phobos2077** [comment]
I don't think I touched kids stealing behavior in any way. RPU might've changed something about, idk. Someone needs to compare their scripts with vanilla.

As to picking up items from inventory - I added a script for select vendors that removes items of certain types randomly to make you think if it worth killing them or not. I guess it should be possible to remember which items were stolen and make sure they're available on death. A little scripting magic needed.

**Comment by phobos2077** [comment]
> could you please clarify this. do you mean it already exists in latest Ecco release and you suppose I can just edit it to have Tubby preserve items on death?

Yes it's in EcCo. If you want you can just remove that piece of code and recompile the script from source. I'll take a look at this script later and think what to do about it.
