### ISSUE TITLE
gl_pbs_damage_mod.ssl: "PERK_pyromaniac" and "PERK_living_anatomy" bonus damage does not take into account the values from "perks.ini"

### ISSUE THREAD

**Issue by dekrus** [phobos2077/fo2_ecco#5]
In the damage script, the bonus from "PERK_pyromaniac" and "PERK_living_anatomy" is static and does not take into account the new values from "perks.ini".

I think it's worth ensuring that the amount of bonus damage is fetched from the INI file or even directly and "safely" from the game memory, as there is also "set_pyromaniac_mod", although for some reason, there is no "get_pyromaniac_mod" :)

https://github.com/phobos2077/fo2_ecco/blob/8377828645b8dcc57de895e1ba2674acf2b8f83a/scripts_src/_pbs_main/gl_pbs_damage_mod.ssl#L268-L274

В скрипте на расчёт урона бонусы от "PERK_pyromaniac" и "PERK_living_anatomy" являются константами и не меняются при изменении значений в "perks.ini".

Может логичнее сделать так, чтобы величина бонусного урона бралась из INI-файла? Или даже напрямую и "безопасно" из памяти игры, так как есть "set_pyromaniac_mod", хотя почему-то нет "get_pyromaniac_mod" :)

**Comment by phobos2077** [comment]
Мод делается как единое целое, т.е. переработка геймплея. Поэтому не было нужды читать значение из perks.ini. Сейчас значения совпадают, т.е. никакого бага тут нет. 

Перефразируй задачу, т.к. иначе непонятная цель её заведения.

**Comment by dekrus** [comment]
Цель проста - обеспечить совместимость с другими модами (в данном случае, со sfall и его perks.ini).

Но если изначальная задумка не предусматривала возможность изменений со стороны игрока или других модов, то тогда всё ок.

**Comment by phobos2077** [comment]
Сделал.
