### ISSUE TITLE
Drug "Hercules" is bugged under random condition

### ISSUE THREAD

**Issue by Dumbisted** [phobos2077/fo2_ecco#7]
Symptom: When effect of "Hercules" is gone, increased carry weight is not decreasing. Increased Strength is decreasing without any problem, tho.

![스크린샷 2024-05-05 000225](https://github.com/phobos2077/fo2_ecco/assets/52318642/a4ed7742-cd56-492c-ab10-32b8f1fb50f3)
it's been more than a month after used "Hercules", the carry weight is supposed to be 225 but has been fixed as **400**(guess it included bonus 25 weight from +1 strength). Of course, I've not taken any perks that increasing carry weight.

Seems like it happens under some specific condition, but I can't actually figure out what causes it.

-------------------------------------------------------------------------------

EcCo Version: 0.9.3

Sfall Version: 4.4.3.1

Used mods: 
1. RPU v28
2. Maps Updated
3. Fallout2MechanicsMiniRework 1.98v
4. Talking Heads Addon
5. Inventory Filter 2.0.3
6. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
7. Autoclosebox (in example_mods from modderspack)

Don't know whether it's a problem of mod compatibility or EcCo itself. I might should do test it without any other mods.

**Comment by phobos2077** [comment]
Could you upload a save?

**Comment by Dumbisted** [comment]
[SLOT01.zip](https://github.com/phobos2077/fo2_ecco/files/15211894/SLOT01.zip)

Here's the savefile. Strength bonus is gone after the effect burnt out, as it supposed to be.

**Comment by phobos2077** [comment]
Tried to eat 8 Herculeses at a time to go over 999 carry weight limit, with and without Power Armor - after a day it always gets back to normal. It uses regular vanilla drug mechanics that modify base stats and use persistent events for time-delayed effects. I don't know any cases where these events wouldn't fire. But maybe you found some edge case related to event system or bonus stat edge values or some taking/removing power armor at specific time...

In any case, I will put a limit on stacking effects for new drugs to 1 (down from 6 or so) as they weren't really designed to stack. And maybe reduce carry weight increase a little.

**Comment by phobos2077** [comment]
Ok, new version is up. Check if you can reproduce this again and reopen if necessary.
