### ISSUE TITLE
Units died from Flame explosion damage plays idle animation instead of death animation.

### ISSUE THREAD

**Issue by Dumbisted** [phobos2077/fo2_ecco#8]
I've just found the bug while throwing molotov cocktails and firing 40mm IC grenades to enemies.

If the bug happens, dying unit plays idle animation("reloading" animation for humans, for example) instead of death animation, as the title says- then a sprite of their corpse stay as last frame of the idle animation.

![scr00007](https://github.com/phobos2077/fo2_ecco/assets/52318642/97c1ccf3-5f80-4005-919b-b52a9713a84e)
![scr00009](https://github.com/phobos2077/fo2_ecco/assets/52318642/4ca42789-dff2-47db-952c-df57d5d3f57b)

Like these screenshots. They are not living but just a corpse.

Here's a log, search for Kaga encounter part: 
[debug.log](https://github.com/phobos2077/fo2_ecco/files/15447106/debug.log)

--------------------------------

EcCo Version: 0.9.5

Sfall Version: 4.4.3.1 + cnc-ddraw

Used mods:

1. RPU v29
2. Maps Updated
3. Fo2tweaks v12.17
4. Fallout2MechanicsMiniRework 1.98.3v
5. Talking Heads Addon
6. Inventory Filter 2.0.3
7. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
8. Autoclosebox (in example_mods from modderspack)

**Comment by phobos2077** [comment]
Thanks. I'm have seen this bug several times, but still don't understand the exact steps to reproduce. This always happens with IC grenades?

**Comment by Dumbisted** [comment]
I guess so, along with molotov cocktail... but I've not done full test on every units(since I'm not using any debugging stuffs) so not absolutely sure yet.

Incinerator, on the other hand is working well, plays flameboy animation without a problem.

**Comment by phobos2077** [comment]
The issue was Molotov and IC grenades. Fixed for the next release.
