### ISSUE TITLE
Crafting button overlaps interface.

### ISSUE THREAD

**Issue by Dumbisted** [phobos2077/fo2_ecco#9]
![output_scr00017](https://github.com/phobos2077/fo2_ecco/assets/52318642/c627f673-8fa6-472f-8005-900ee0092561)
(That "error" in the dialog happens somtimes. Don't know which mod is causing it)

![output_scr00016](https://github.com/phobos2077/fo2_ecco/assets/52318642/d7495b58-71a8-40b3-abf5-b401f58335bd)

Happens in conversation dialog interface. At least the button does nothing on click while overlapping like that. 

Resolution: 3840x2160(Sfall) + 960x540(HRP Config) + cnc-ddraw

Other noticeable settings in HRP Config:
1. IFACE_BAR_MODE=0
2. SCALE_BUTTONS_AND_TEXT_MENU=1
3. DIALOG_SCRN_BACKGROUND=1
4. DIALOG_SCRN_ART_FIX=1

---------------------------------------------------------------------------------

EcCo Version: v0.9.6

Other mods:
1. RPU v29
2. Maps Updated
3. Fo2tweaks v12.17
4. Fallout2MechanicsMiniRework 1.98.3v
5. Talking Heads Addon
6. Inventory Filter 2.0.3
7. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
8. Autoclosebox (in example_mods from modderspack)

**Comment by phobos2077** [comment]
Huh, I was sure I fixed this. Try disabling external HRP.

**Comment by phobos2077** [comment]
Looks like this option is causing this, `DIALOG_SCRN_BACKGROUND=1`, you can disable it for now.
